<?php

use \Drupal\Core\Entity\EntityInterface;
use \Drupal\Core\Cache\Cache;

define('BLOCK_PANELIZER_USAGE_CACHE_TAG_VIEW_MODES', 'block_panelizer_usage:view_modes');
define('BLOCK_PANELIZER_USAGE_CACHE_TAG_BLOCK_REGIONS', 'block_panelizer_usage:block_regions');
define('BLOCK_PANELIZER_USAGE_CACHE_TAG_PANELIZERED_NODES', 'block_panelizer_usage:panelizered_nodes');

/**
 * Implements hook_entity_presave().
 *
 * Invalidates all the cache tags set in the views.
 */
function block_panelizer_usage_entity_presave(EntityInterface $entity) {

  if ($entity->getEntityTypeId() == 'entity_view_display') {
    Cache::invalidateTags([BLOCK_PANELIZER_USAGE_CACHE_TAG_VIEW_MODES]);
  }

  elseif ($entity->getEntityTypeId() == 'block') {
    Cache::invalidateTags([BLOCK_PANELIZER_USAGE_CACHE_TAG_BLOCK_REGIONS]);
  }

  elseif ($entity->getEntityTypeId() == 'node' && $entity->hasField('panelizer')) {
    Cache::invalidateTags([BLOCK_PANELIZER_USAGE_CACHE_TAG_PANELIZERED_NODES]);
  }
}